name: CI

on:
  push:
    paths-ignore:
      - .github/*
      - README.md
  pull_request:
    paths-ignore:
      - .github/*
      - README.md

jobs:
  test:
    # if: github.event_name == 'pull_request'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Add npm token to .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.github_token }}" >> $env:USERPROFILE\.npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Compile for CI
        run: yarn compile:ci

      # - name: Run unit tests
      #   run: yarn test:unit

      - name: Run test
        run: yarn test -m "Main and child window visibility"

      - name: list
        shell: pwsh
        run: |
          Get-Location
          Get-ChildItem -Path $env:APPDATA -Recurse -Force

      # - name: Get AppData Files
      #   shell: pwsh
      #   run: |
      #     $appDataFiles = Get-ChildItem -Path $env:APPDATA -File -Recurse | Select-Object -ExpandProperty FullName
      #     $zipPath = "$env:GITHUB_WORKSPACE/appdata_files.zip"
      #     Compress-Archive -Path $appDataFiles -DestinationPath $zipPath

      # - name: Display AppData File Contents
      #   run: |
      #     cat $env:GITHUB_WORKSPACE/appdata_files.zip
